# Generated by Django 6.0.4 on 2026-05-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstats",
            name="puzzle_best_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="puzzle_games_played",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="puzzle_total_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="puzzles_solved_total",
            field=models.IntegerField(default=0),
        ),
    ]
