# Generated by Django 5.2.13 on 2026-05-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_game", "0002_playerstats_puzzle_best_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("theme", "Board Theme"),
                            ("frame", "Avatar Frame"),
                            ("title", "Title"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.IntegerField(default=100)),
                ("value", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("preview_light", models.CharField(blank=True, max_length=20)),
                ("preview_dark", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="opening_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="avatar_frame",
            field=models.CharField(default="none", max_length=50),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="board_theme",
            field=models.CharField(default="classic", max_length=50),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="daily_login_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="favorite_opening",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="last_bonus_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="owned_items",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="total_playtime",
            field=models.IntegerField(default=0),
        ),
    ]
